# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_use_teams', 'Can use teams'),), 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
