# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounce",
            name="bounces",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
