# Generated by Django 4.2.16 on 2025-01-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proof", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proof",
            options={"verbose_name": "Proof", "verbose_name_plural": "Proofs"},
        ),
    ]
