# Generated by Django 5.2.10 on 2026-02-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'Proof', 'verbose_name_plural': 'Proofs'},
        ),
    ]
