from django import template
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe

import markdown as markdown_lib
import nh3

register = template.Library()


@register.filter(is_safe=True)
def markdown(value, arg=""):
    """
    Taken from Django 1.4 to avoid deprecation warnings

    Runs Markdown over a given value, optionally using various
    extensions python-markdown supports.

    Syntax::

        {{ value|markdown:"extension1_name,extension2_name..." }}

    To enable safe mode, which strips raw HTML and only returns HTML
    generated by actual Markdown syntax, pass "safe" as the first
    extension in the list.

    If the version of Markdown in use does not support extensions,
    they will be silently ignored.

    """
    html = markdown_lib.markdown(force_str(value))
    clean_html = nh3.clean(html)
    return mark_safe(clean_html)
