# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180417_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date deactivated'),
        ),
    ]
