# Generated by Django 2.1.7 on 2019-03-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190309_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeduser',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taggeduser',
            name='tag_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='account.UserTag'),
        ),
    ]
