# Generated by Django 2.1.7 on 2019-03-09 11:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20190309_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeduser',
            name='tag',
        ),
        migrations.RenameField(
            model_name='taggeduser',
            old_name='tag_new',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='account.TaggedUser', to='account.UserTag', verbose_name='Tags'),
        ),
    ]
