# Generated by Django 3.0.5 on 2020-06-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20200527_1240'),
    ]

    operations = [
        migrations.RenameModel('AccountBlacklist', 'AccountBlocklist')
    ]
