# Generated by Django 3.0.8 on 2020-08-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_auto_20200608_1111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountblocklist",
            options={
                "verbose_name": "Blocklist entry",
                "verbose_name_plural": "Blocklist",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="newsletter",
        ),
    ]
