# Generated by Django 3.1.4 on 2020-12-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_auto_20200812_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
