# Generated by Django 3.1.8 on 2021-04-28 10:25

from django.db import migrations


def copy_email_address(apps, schema_editor):
    User = apps.get_model('account', 'User')
    for user in User.objects.all():
        user.email_ci = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_user_email_ci'),
    ]

    operations = [
        migrations.RunPython(copy_email_address),
    ]
