# Generated by Django 3.2.8 on 2021-12-03 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0031_auto_20210517_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=False, choices=settings.LANGUAGES, default="de", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Optional. Affiliation will be shown next to your name",
                max_length=255,
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization_url",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Organization Website"
            ),
        ),
    ]
