# Generated by Django 3.2.12 on 2022-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0033_auto_20220215_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
