# Generated by Django 4.2.14 on 2024-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0036_alter_application_user_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountblocklist",
            name="full_name",
            field=models.TextField(blank=True),
        ),
    ]
