# Generated by Django 5.2.1 on 2025-09-03 12:38


from django.db import migrations, models
from django.db.models.functions import Lower


def lowercase_username(apps, schema_editor):
    User = apps.get_model("account", "User")
    for user in User.objects.exclude(username=Lower(models.F("username"))):
        user.username = user.username.lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_application_allowed_origins_and_more"),
    ]

    operations = [migrations.RunPython(lowercase_username, migrations.RunPython.noop)]
