# Generated by Django 5.2.12 on 2026-04-15 10:47

import froide.helper.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_application_authorization_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=froide.helper.language.get_language_choices, default=froide.helper.language.get_default_language, help_text='Determines the default language of communication with you.', max_length=10, verbose_name='Language'),
        ),
    ]
