# Generated by Django 5.2.12 on 2026-06-11 14:30

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Client secret for authentication', max_length=255),
        ),
    ]
