# Generated by Django 2.1.4 on 2019-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20181116_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
