# Generated by Django 2.1.4 on 2019-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_rule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidance',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
