# Generated by Django 2.2.4 on 2020-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_guidance_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='mail_intent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
