# Generated by Django 2.2.4 on 2020-03-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_auto_20200303_1117'),
        ('guide', '0005_action_mail_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='letter_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter.LetterTemplate'),
        ),
    ]
