# Generated by Django 3.1.6 on 2021-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_action_letter_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Guide action', 'verbose_name_plural': 'Guide actions'},
        ),
        migrations.AddField(
            model_name='guidance',
            name='matches',
            field=models.JSONField(null=True),
        ),
    ]
