# Generated by Django 5.2.6 on 2026-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20210223_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='params',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='matches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
