# Generated by Django 3.2.12 on 2022-03-14 12:32

from django.db import migrations

import froide.helper.fields
import froide.helper.storage
import froide.organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=froide.helper.fields.SVGAndImageField(
                blank=True,
                null=True,
                storage=froide.helper.storage.HashedFilenameStorage(),
                upload_to=froide.organization.models.logo_path,
            ),
        ),
    ]
