# Generated by Django 4.0.7 on 2022-10-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('organization', '0003_organization_display_option_and_more'), ('organization', '0004_remove_organization_display_option')]

    dependencies = [
        ('organization', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_in_list',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
