# Generated by Django 2.1.4 on 2019-01-18 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accesstoken", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
