# Generated by Django 2.1.11 on 2019-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='request_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='request_match',
            field=models.TextField(blank=True),
        ),
    ]
