# Generated by Django 3.0.8 on 2020-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_auto_20190826_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="report_url",
            field=models.URLField(blank=True),
        ),
    ]
