# Generated by Django 5.2.6 on 2025-12-08 11:55

import froide.helper.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_campaign_report_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=froide.helper.storage.HashedFilenameStorage(),
                upload_to="campaign-logos",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
