# Generated by Django 5.2.6 on 2026-03-23 16:37

import froide.helper.fields
import froide.helper.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0008_campaign_logo_campaign_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="logo",
            field=froide.helper.fields.SVGAndImageField(
                blank=True,
                null=True,
                storage=froide.helper.storage.HashedFilenameStorage(),
                upload_to="campaign-logos",
            ),
        ),
    ]
