# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0003_auto_20180508_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
