# Generated by Django 2.1.7 on 2019-03-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0005_auto_20190309_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='georegion',
            options={'ordering': ('name',), 'verbose_name': 'Geo Region', 'verbose_name_plural': 'Geo Regions'},
        ),
    ]
