# Generated by Django 2.1.7 on 2019-03-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0006_auto_20190325_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='georegion',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='georegion',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
