# Generated by Django 2.1.7 on 2019-03-25 18:56

from django.db import migrations


def make_nodes(apps, schema_editor):
    from treebeard.mp_tree import MP_Node

    from froide.helper.tree_utils import _inc_path, add_children

    def get_children(node):
        return GeoRegion.objects.filter(part_of=node).order_by("name")

    GeoRegion = apps.get_model("georegion", "GeoRegion")

    root_regions = GeoRegion.objects.filter(part_of__isnull=True).order_by("name")
    last_root = None
    for georegion in root_regions:
        if last_root is None:
            newpath = MP_Node._get_path(None, 1, 1)
        else:
            newpath = _inc_path(last_root.path)

        georegion.depth = 1
        georegion.path = newpath
        georegion.save()
        last_root = georegion

    for georegion in root_regions:
        add_children(georegion, get_children)


class Migration(migrations.Migration):
    dependencies = [
        ("georegion", "0007_auto_20190325_1956"),
    ]

    operations = [migrations.RunPython(make_nodes)]
