# Generated by Django 3.2.4 on 2021-08-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("georegion", "0009_auto_20190325_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="georegion",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
