# Generated by Django 3.2.4 on 2021-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("georegion", "0010_georegion_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="georegion",
            name="invalid_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
