# Generated by Django 5.2.4 on 2025-08-06 15:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0011_georegion_invalid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='geom_detail',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='geometry detail'),
        ),
        migrations.AddField(
            model_name='georegion',
            name='osm_tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='georegion',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
