# Generated by Django 5.2.4 on 2025-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0012_georegion_geom_detail_georegion_osm_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georegion',
            name='region_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
