# Generated by Django 5.2.12 on 2026-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0013_alter_georegion_region_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='related',
            field=models.ManyToManyField(blank=True, to='georegion.georegion', verbose_name='Related Regions'),
        ),
    ]
