# Generated by Django 5.2.10 on 2026-04-22 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('email_confirmed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp of creation')),
                ('last_alert', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp of last alert')),
                ('interval', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10)),
                ('query', models.TextField()),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user', None), models.Q(('email', ''), _negated=True)), models.Q(models.Q(('user', None), _negated=True), ('email', '')), _connector='OR'), name='user_or_email')],
            },
        ),
    ]
