# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 14:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '__first__'),
        ('publicbody', '0012_auto_20180227_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbody',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='publicbody',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='georegion.GeoRegion'),
        ),
    ]
