# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0013_auto_20180306_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbody',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.GeoRegion'),
        ),
    ]
