# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georegion', '0003_auto_20180306_1730'),
        ('publicbody', '0014_auto_20180306_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.GeoRegion'),
        ),
    ]
