# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 08:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0016_publicbody_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbody',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.GeoRegion'),
        ),
    ]
