# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0017_auto_20180313_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georegion.GeoRegion'),
        ),
    ]
