# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0018_auto_20180409_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='foilaw',
            name='law_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='law type'),
        ),
    ]
