# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 10:35
from __future__ import unicode_literals

from django.db import migrations
import froide.publicbody.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0020_foilaw_requires_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedPublicBody',
            fields=[
            ],
            options={
                'verbose_name': 'Proposed Public Body',
                'verbose_name_plural': 'Proposed Public Bodies',
                'proxy': True,
                'indexes': [],
            },
            bases=('publicbody.publicbody',),
            managers=[
                ('objects', froide.publicbody.models.ProposedPublicBodyManager()),
            ],
        ),
    ]
