# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 14:16
from __future__ import unicode_literals

from django.db import migrations


def move_region_to_regions(apps, schema_editor):
    PublicBody = apps.get_model('publicbody', 'PublicBody')
    for pb in PublicBody.objects.filter(region__isnull=False):
        pb.regions.add(pb.region)


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0023_auto_20181114_1515'),
    ]

    operations = [
        migrations.RunPython(move_region_to_regions),
    ]
