# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0024_auto_20181114_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicbody',
            name='region',
        ),
    ]
