# Generated by Django 3.1.4 on 2021-02-03 14:05

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def forwards_func(apps, schema_editor):
    FoiLaw = apps.get_model("publicbody", "FoiLaw")
    FoiLawTranslation = apps.get_model("publicbody", "FoiLawTranslation")

    for obj in FoiLaw.objects.all():
        FoiLawTranslation.objects.create(
            master_id=obj.pk,
            language_code=settings.LANGUAGE_CODE,
            name=obj._name,
            slug=obj._slug,
            description=obj._description,
            long_description=obj._long_description,
            request_note=obj._request_note,
            letter_start=obj._letter_start,
            letter_end=obj._letter_end,
            refusal_reasons=obj._refusal_reasons,
        )


def backwards_func(apps, schema_editor):
    FoiLaw = apps.get_model("publicbody", "FoiLaw")
    FoiLawTranslation = apps.get_model("publicbody", "FoiLawTranslation")

    for obj in FoiLaw.objects.all():
        translation = _get_translation(obj, FoiLawTranslation)
        obj._name = translation.name
        obj._slug = translation.slug
        obj._description = translation.description
        obj._long_description = translation.long_description
        obj._request_note = translation.request_note
        obj._letter_start = translation.letter_start
        obj._letter_end = translation.letter_end
        obj._refusal_reasons = translation.refusal_reasons
        obj.save()  # Note this only calls Model.save()


def _get_translation(object, MyModelTranslation):
    translations = MyModelTranslation.objects.filter(master_id=object.pk)
    try:
        # Try default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            # Try default language
            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0034_add_translation_laws"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
