# Generated by Django 3.1.4 on 2021-02-03 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0035_migrate_translatable_fields_foilaw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foilaw",
            name="_description",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_letter_end",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_letter_start",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_long_description",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_name",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_refusal_reasons",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_request_note",
        ),
        migrations.RemoveField(
            model_name="foilaw",
            name="_slug",
        ),
    ]
