# Generated by Django 3.1.6 on 2021-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0036_auto_20210203_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='foilawtranslation',
            name='legal_text',
            field=models.TextField(blank=True, verbose_name='Legal Text'),
        ),
    ]
