# Generated by Django 3.1.6 on 2021-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0037_foilawtranslation_legal_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="foilaw",
            name="scale_of_fees",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Scale of fees URL"
            ),
        ),
    ]
