# Generated by Django 3.2.8 on 2021-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0038_foilaw_scale_of_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicbody",
            name="alternative_emails",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
