# Generated by Django 4.0.7 on 2022-10-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0040_alter_foilaw_options'),
        ('publicbody', '0042_remove_publicbody_change_proposals_and_more'),
    ]

    operations = [
    ]
