# Generated by Django 4.2.1 on 2023-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0043_merge_20221019_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicbody",
            name="laws",
            field=models.ManyToManyField(
                blank=True,
                to="publicbody.foilaw",
                verbose_name="Freedom of Information Laws",
            ),
        ),
    ]
