# Generated by Django 4.2.4 on 2023-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0044_alter_publicbody_laws"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisdiction",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
