# Generated by Django 4.2.4 on 2024-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0045_jurisdiction_last_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="foilawtranslation",
            name="overdue_reply",
            field=models.TextField(blank=True, verbose_name="overdue reply"),
        ),
    ]
