# Generated by Django 4.2.4 on 2024-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0047_alter_classification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicbodychangeproposal",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
