# Generated by Django 4.2.14 on 2024-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicbody", "0048_publicbodychangeproposal_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicbody",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
    ]
