# Generated by Django 4.2.16 on 2025-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0050_alter_publicbody_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpublicbody',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedpublicbody',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PublicBodyTag',
        ),
        migrations.DeleteModel(
            name='TaggedPublicBody',
        ),
    ]
