# Generated by Django 5.2.10 on 2026-03-31 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0051_remove_taggedpublicbody_content_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBodyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=True, verbose_name='confirmed')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('fax', models.CharField(blank=True, default='', max_length=50, verbose_name='Fax')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_body_contacts', to='publicbody.category')),
                ('publicbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='publicbody.publicbody')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Public Body Contact',
                'verbose_name_plural': 'Public Body Contacts',
                'constraints': [models.UniqueConstraint(condition=models.Q(('confirmed', True)), fields=('publicbody', 'category'), name='unique_publicbody_category'), models.UniqueConstraint(condition=models.Q(('confirmed', False)), fields=('publicbody', 'category', 'user'), name='unique_publicbody_category_draft')],
            },
        ),
    ]
