# Generated by Django 5.2.10 on 2026-04-02 10:10

from django.db import migrations

def move_alternative_emails_to_contact(apps, schema_editor):
    PublicBody = apps.get_model('publicbody', 'PublicBody')
    Category = apps.get_model('publicbody', 'Category')
    PublicBodyContact = apps.get_model('publicbody', 'PublicBodyContact')

    category_cache = {}

    pbs = PublicBody.objects.filter(alternative_emails__isnull=False).exclude(alternative_emails={})

    for pb in pbs:
        if not pb.alternative_emails:
            continue
        for key, email in pb.alternative_emails.items():
            if key not in category_cache:
                category = Category.objects.get(name=key)
                category_cache[key] = category
            else:
                category = category_cache[key]
            PublicBodyContact.objects.update_or_create(
                publicbody=pb,
                category=category,
                defaults={
                    "email": email,
                    "confirmed": True
            })



class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0052_publicbodycontact'),
    ]

    operations = [
        migrations.RunPython(move_alternative_emails_to_contact)
    ]
