# Generated by Django 5.2.10 on 2026-04-02 13:15

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0053_auto_20260402_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedPublicBodyContact',
            fields=[
            ],
            options={
                'verbose_name': 'Proposed Public Body Contact',
                'verbose_name_plural': 'Proposed Public Body Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('publicbody.publicbodycontact',),
        ),
        migrations.AlterModelManagers(
            name='publicbodycontact',
            managers=[
                ('non_filtered_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='publicbody',
            name='alternative_emails',
        ),
        migrations.AddField(
            model_name='foilaw',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.category'),
        ),
    ]
