# Generated by Django 5.2.12 on 2026-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0054_proposedpublicbodycontact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foilawtranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='foilawtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='publicbody_foilaw_translation_uniq_lang'),
        ),
    ]
