# Generated by Django 5.2.12 on 2026-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0054_proposedpublicbodycontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbody',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
