import '../styles/main.scss'

import './snippets/bootstrap.ts'
import './snippets/copy-text'
import './snippets/form-ajax.ts'
import './snippets/inline-edit-forms.ts'
import './snippets/misc.ts'
import './snippets/search.ts'
import './snippets/share-links.ts'
import './snippets/color-mode.ts'
