# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import filingcabinet.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20180521_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageannotation',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=filingcabinet.models.get_page_annotation_filename),
        ),
    ]
