# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20180807_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='document',
        ),
        migrations.RemoveField(
            model_name='pageannotation',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageannotation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageAnnotation',
        ),
    ]
