# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_documentcollection'),
        ('filingcabinet', '0004_auto_20180810_1642')
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcollection',
            name='documents',
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='document_documentcollection', through='filingcabinet.CollectionDocument', to=settings.FILINGCABINET_DOCUMENT_MODEL),
        ),
    ]
