# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 17:10
from __future__ import unicode_literals

from django.db import migrations


def set_fields_from_original(apps, schema_editor):
    Document = apps.get_model('document', 'Document')

    for doc in Document.objects.filter(original__isnull=False):
        doc.foirequest = doc.original.belongs_to.request
        doc.publicbody = doc.original.belongs_to.sender_public_body
        doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20180810_1908'),
    ]

    operations = [
        migrations.RunPython(set_fields_from_original),
    ]
