# Generated by Django 2.1.9 on 2019-08-06 19:21

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20180810_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English')], default='de', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='+', through='filingcabinet.TaggedDocument', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
