# Generated by Django 2.2.4 on 2019-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20191001_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcollection',
            options={'verbose_name': 'document collection', 'verbose_name_plural': 'document collections'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
