# Generated by Django 3.0.7 on 2020-06-22 11:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_auto_20200117_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='outline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
