# Generated by Django 3.1.6 on 2021-03-23 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0023_auto_20200622_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="documentcollection",
            name="listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="documentcollection",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
