# Generated by Django 3.2.4 on 2021-07-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0026_auto_20210603_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=40, null=True
            ),
        ),
    ]
