# Generated by Django 3.2.12 on 2022-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document", "0027_alter_document_content_hash"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="document_document_chash_idx",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("content_hash__isnull", False)),
                fields=["content_hash"],
                name="fc_document_chash_idx",
            ),
        ),
    ]
