# Generated by Django 3.2.14 on 2022-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0055_foiattachment_is_moderated'),
        ('document', '0028_auto_20220404_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='foirequests',
            field=models.ManyToManyField(blank=True, to='foirequest.FoiRequest'),
        ),
    ]
