# Generated by Django 4.2.16 on 2025-04-09 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("filingcabinet", "0030_collectiondirectory_description"),
        ("document", "0029_documentcollection_foirequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcollection",
            name="allow_zip_download",
            field=models.BooleanField(default=True),
        )
    ]
