# Generated by Django 5.2.10 on 2026-02-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_documentcollection_allow_zip_download'),
        ('filingcabinet', '0031_alter_collectiondirectory_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s', through='filingcabinet.CollectionDocument', through_fields=('collection', 'document'), to=settings.FILINGCABINET_DOCUMENT_MODEL),
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
