# Generated by Django 5.2.12 on 2026-04-20 10:05

import filingcabinet.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_alter_document_updated_at_alter_document_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, choices=filingcabinet.language.get_language_choices, default=filingcabinet.language.get_default_language, max_length=10),
        ),
    ]
