# Generated by Django 5.0.14 on 2025-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_upload_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='state',
            field=models.CharField(choices=[('initial', 'Initial'), ('receiving', 'Receiving'), ('saving', 'Saving'), ('done', 'Done')], default='initial', max_length=50),
        ),
    ]
