# Generated by Django 3.0.8 on 2020-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_problemreport_escalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='escalation',
            field=models.TextField(blank=True),
        ),
    ]
