# Generated by Django 4.2.1 on 2023-05-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problem", "0006_problemreport_escalation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemreport",
            name="kind",
            field=models.CharField(
                choices=[
                    ("message_not_delivered", "Your message was not delivered."),
                    ("attachment_broken", "The attachments don't seem to work."),
                    ("redaction_needed", "More redactions are needed."),
                    (
                        "foi_help_needed",
                        "You need help to understand or reply to this message.",
                    ),
                    ("other", "Something else..."),
                    ("not_foi", "This is not a proper FOI request."),
                    ("not_nice", "Content is against netiquette."),
                    ("info_outdated", "Published information is outdated."),
                    ("info_wrong", "Published information is wrong."),
                    (
                        "bounce_publicbody",
                        "You received a bounce mail from the public body.",
                    ),
                    (
                        "mail_inauthentic",
                        "Received mail does not pass authenticity checks.",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
