export const SET_PUBLICBODY = 'SET_PUBLICBODY'
export const SET_PUBLICBODIES = 'SET_PUBLICBODIES'
export const SET_PUBLICBODY_DETAIL = 'SET_PUBLICBODY_DETAIL'
export const SET_PUBLICBODIES_DETAIL = 'SET_PUBLICBODIES_DETAIL'
export const SET_USER = 'SET_USER'

export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'
export const UPDATE_BODY = 'UPDATE_BODY'

export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_PRIVATE = 'UPDATE_PRIVATE'
