# Generated by Django 3.1.8 on 2021-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="froidecomment",
            name="is_removed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.',
                verbose_name="is removed",
            ),
        ),
        migrations.AlterField(
            model_name="froidecomment",
            name="object_pk",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="object ID"
            ),
        ),
    ]
