# Generated by Django 4.0.7 on 2022-09-16 09:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("comments", "0002_auto_20210505_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="froidecomment",
            name="is_moderation",
            field=models.BooleanField(default=False),
        )
    ]
