# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0007_auto_20171121_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foirequest',
            options={'get_latest_by': 'last_message', 'ordering': ('-last_message',), 'permissions': (('see_private', 'Can see private requests'), ('create_batch', 'Create batch requests')), 'verbose_name': 'Freedom of Information Request', 'verbose_name_plural': 'Freedom of Information Requests'},
        ),
    ]
