# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0014_auto_20180111_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredmessage',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
