# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0012_auto_20180227_1926'),
        ('foirequest', '0015_deferredmessage_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiproject',
            name='publicbodies',
            field=models.ManyToManyField(blank=True, to='publicbody.PublicBody'),
        ),
    ]
