# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import froide.foirequest.models.attachment
import froide.helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0016_foiproject_publicbodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiattachment',
            name='file',
            field=models.FileField(max_length=255, storage=froide.helper.storage.HashedFilenameStorage(), upload_to=froide.foirequest.models.attachment.upload_to, verbose_name='File'),
        ),
    ]
