# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0017_auto_20180405_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdraft',
            name='law_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
