# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0019_foiattachment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiattachment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='foiattachment',
            unique_together=set([('belongs_to', 'name')]),
        ),
    ]
