# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0020_auto_20180605_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='foimessage',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('post', 'Postal mail'), ('fax', 'Fax'), ('phone', 'Phone call'), ('visit', 'Personal visit')], default='email', max_length=10),
        ),
    ]
