# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0023_remove_foimessage_is_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foimessage',
            name='original',
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status',
            field=models.CharField(blank=True, choices=[('unknown', 'unknown'), ('sending', 'sending'), ('sent', 'sent'), ('received', 'received'), ('read', 'read'), ('deferred', 'deferred'), ('bounced', 'bounced'), ('expired', 'expired'), ('failed', 'failed')], max_length=32),
        ),
    ]
