# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0025_foimessage_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
