# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0026_deliverystatus_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiattachment',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original', to='document.Document'),
        ),
    ]
