# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0028_auto_20180807_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdraft',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestdraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
