# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0029_auto_20180924_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredmessage',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deferredmessage',
            name='spam',
            field=models.NullBooleanField(default=False),
        ),
    ]
