# Generated by Django 2.1.5 on 2019-02-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0034_auto_20190129_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='foirequest',
            name='not_publishable',
            field=models.BooleanField(default=False, verbose_name='Not publishable'),
        ),
        migrations.AlterField(
            model_name='foiattachment',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foiattachment_set', to='foirequest.FoiMessage', verbose_name='Belongs to request'),
        ),
    ]
