# Generated by Django 2.1.7 on 2019-03-09 10:53

from django.db import migrations, models
import froide.foirequest.models.attachment
import froide.helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0036_auto_20190209_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiattachment',
            name='file',
            field=models.FileField(db_index=True, max_length=255, storage=froide.helper.storage.HashedFilenameStorage(), upload_to=froide.foirequest.models.attachment.upload_to, verbose_name='File'),
        ),
    ]
