# Generated by Django 2.1.7 on 2019-03-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180111_1347'),
        ('foirequest', '0038_foirequest_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='foirequest',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.Team', verbose_name='Team'),
        ),
    ]
