# Generated by Django 2.1.9 on 2019-07-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0039_foirequest_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiattachment',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foiattachment',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foiattachment_set', to='foirequest.FoiMessage', verbose_name='Belongs to message'),
        ),
    ]
