# Generated by Django 2.2.2 on 2019-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0040_auto_20190718_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foimessage',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('post', 'Postal mail'), ('fax', 'Fax'), ('upload', 'Upload'), ('phone', 'Phone call'), ('visit', 'Personal visit')], default='email', max_length=10),
        ),
    ]
