# Generated by Django 3.0.8 on 2020-07-10 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0042_auto_20200710_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverystatus",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
