# Generated by Django 3.0.8 on 2020-07-28 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0043_auto_20200710_1845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foievent",
            name="context_json",
            field=models.JSONField(verbose_name="Context JSON"),
        ),
        migrations.AlterField(
            model_name="foievent",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
    ]
