# Generated by Django 3.2.4 on 2021-08-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0050_auto_20210419_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="email_headers",
            field=models.JSONField(default=None, null=True),
        ),
    ]
