# Generated by Django 3.2.8 on 2021-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0052_alter_foirequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foimessage",
            name="email_headers",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
