# Generated by Django 3.2.12 on 2022-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0055_foiattachment_is_moderated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foimessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("post", "postal mail"),
                    ("fax", "fax"),
                    ("upload", "upload"),
                    ("phone", "phone call"),
                    ("visit", "visit in person"),
                    ("import", "automatically imported"),
                ],
                default="email",
                max_length=10,
            ),
        ),
    ]
