# Generated by Django 4.0.7 on 2022-10-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("foirequest", "0056_alter_foimessage_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="redacted_content_anon",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foimessage",
            name="redacted_content_auth",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="messagetag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=100, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="taggedfoiproject",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedfoirequest",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
    ]
