# Generated by Django 4.0.7 on 2022-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0057_foimessage_redacted_content_anon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foirequest",
            old_name="first_message",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="foirequest",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Created at"
            ),
        ),
    ]
