# Generated by Django 4.0.8 on 2022-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0058_remove_foirequest_first_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foirequest",
            name="no_index",
            field=models.BooleanField(
                default=False, verbose_name="Disable search machine indexing"
            ),
        ),
    ]
