# Generated by Django 4.0.7 on 2022-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0059_foirequest_no_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="foirequest",
            name="banner",
            field=models.TextField(
                blank=True, verbose_name="Show extra info on request page"
            ),
        ),
    ]
