# Generated by Django 4.2.1 on 2023-06-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0062_alter_foiattachment_belongs_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foirequest",
            name="costs",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Cost of Information",
            ),
        ),
    ]
