# Generated by Django 4.2.4 on 2023-11-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0064_foimessage_confirmation_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="foirequest",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
