# Generated by Django 4.2.4 on 2023-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0064_foimessage_confirmation_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="foirequest",
            name="description_redacted",
            field=models.TextField(blank=True, verbose_name="Redacted Description"),
        ),
    ]
