# Generated by Django 4.2.4 on 2024-01-02 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0065_foimessage_last_modified_at_and_more"),
        ("foirequest", "0065_foirequest_description_redacted"),
    ]

    operations = []
