# Generated by Django 4.2.4 on 2024-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0066_merge_20240102_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="is_draft",
            field=models.BooleanField(
                default=False, verbose_name="is message a draft?"
            ),
        ),
    ]
