# Generated by Django 5.0.6 on 2024-06-10 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0066_merge_20240102_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foiproject",
            options={
                "ordering": ("-last_update",),
                "verbose_name": "FOI Project",
                "verbose_name_plural": "FOI Projects",
            },
        ),
    ]
