# Generated by Django 4.2.16 on 2024-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("foirequest", "0068_foimessage_is_draft_foimessage_is_registered"),
        ("foirequest", "0069_remove_foimessage_is_registered_and_more"),
        ("foirequest", "0070_rename_registered_mail_foimessage_registered_mail_date"),
    ]

    dependencies = [
        ("foirequest", "0067_alter_foiproject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="is_draft",
            field=models.BooleanField(
                default=False, verbose_name="is message a draft?"
            ),
        ),
        migrations.AddField(
            model_name="foimessage",
            name="registered_mail_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Registered mail date"
            ),
        ),
    ]
