# Generated by Django 4.2.4 on 2024-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0067_alter_foiproject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="foimessage",
            name="is_draft",
            field=models.BooleanField(
                default=False, verbose_name="is message a draft?"
            ),
        ),
        migrations.AddField(
            model_name="foimessage",
            name="is_registered",
            field=models.BooleanField(
                default=False, verbose_name="is message registered mail?"
            ),
        ),
    ]
