# Generated by Django 4.2.16 on 2024-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0068_foimessage_is_draft_foimessage_registered_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foimessage",
            name="plaintext",
            field=models.TextField(blank=True, default="", verbose_name="plain text"),
        ),
    ]
