# Generated by Django 4.2.4 on 2024-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0068_foimessage_is_draft_foimessage_is_registered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foimessage",
            name="is_registered",
        ),
        migrations.AddField(
            model_name="foimessage",
            name="registered_mail",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Registered mail date"
            ),
        ),
    ]
