# Generated by Django 4.2.16 on 2025-01-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0069_alter_foimessage_plaintext"),
    ]

    operations = [
        migrations.AddField(
            model_name="foirequest",
            name="redacted_description_anon",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foirequest",
            name="redacted_description_auth",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foirequest",
            name="rendered_description_anon",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foirequest",
            name="rendered_description_auth",
            field=models.TextField(blank=True, null=True),
        ),
    ]
