# Generated by Django 4.2.14 on 2024-09-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0069_remove_foimessage_is_registered_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foimessage",
            old_name="registered_mail",
            new_name="registered_mail_date",
        ),
    ]
