# Generated by Django 4.2.16 on 2025-02-24 15:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0070_foirequest_redacted_description_anon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoiMessageDraft",
            fields=[],
            options={
                "verbose_name": "Freedom of Information Message Draft",
                "verbose_name_plural": "Freedom of Information Message Drafts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("foirequest.foimessage",),
        ),
        migrations.AddField(
            model_name="foiattachment",
            name="approved_timestamp",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
