# Generated by Django 4.2.16 on 2025-03-18 12:42

from django.db import migrations
from django.db.models import Q


def null_empty_cached_fields(apps, schema_editor):
    FoiRequest = apps.get_model("foirequest", "FoiRequest")
    for req in FoiRequest.objects.filter(
        Q(redacted_description_auth="")
        | Q(redacted_description_anon="")
        | Q(rendered_description_auth="")
        | Q(rendered_description_anon="")
    ):
        req.redacted_description_anon = None
        req.redacted_description_auth = None
        req.rendered_description_anon = None
        req.rendered_description_auth = None
        req.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0071_foimessagedraft_alter_foimessage_managers_and_more"),
    ]

    operations = [migrations.RunPython(null_empty_cached_fields, lambda x, y: None)]
