# Generated by Django 5.2.1 on 2025-09-02 09:30

from django.db import migrations, models
from django.db.models.functions import Lower


def lowercase_secret_address(apps, schema_editor):
    FoiRequest = apps.get_model("foirequest", "FoiRequest")
    for request in FoiRequest.objects.exclude(
        secret_address=Lower(models.F("secret_address"))
    ):
        request.secret_address = request.secret_address.lower()
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0072_foirequest_null_empty_cached_fields"),
    ]

    operations = [
        migrations.RunPython(lowercase_secret_address, migrations.RunPython.noop),
    ]
