# Generated by Django 5.2.10 on 2026-02-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0073_lowercase_foirequest_secret_address'),
        ('proof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdraft',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proof.proof'),
        ),
    ]
