# Generated by Django 5.2.12 on 2026-04-15 10:47

import froide.helper.language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0074_requestdraft_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foiproject',
            name='language',
            field=models.CharField(blank=True, choices=froide.helper.language.get_language_choices, default=froide.helper.language.get_default_language, max_length=10),
        ),
        migrations.AlterField(
            model_name='foirequest',
            name='language',
            field=models.CharField(blank=True, choices=froide.helper.language.get_language_choices, default=froide.helper.language.get_default_language, max_length=10),
        ),
    ]
