# Generated by Django 5.2.6 on 2026-02-23 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('foirequest', '0074_requestdraft_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoiRequestLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foirequest.foirequest')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='foirequest__content_fb0636_idx')],
            },
        ),
    ]
