# Generated by Django 5.2.10 on 2026-05-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0075_alter_foiproject_language_alter_foirequest_language'),
        ('publicbody', '0054_proposedpublicbodycontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdraft',
            name='responsibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicbody.category'),
        ),
    ]
