# Generated by Django 5.2.12 on 2026-08-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequest", "0075_alter_foiproject_language_alter_foirequest_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foimessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("post", "postal mail"),
                    ("fax", "fax"),
                    ("form", "form"),
                    ("upload", "upload"),
                    ("phone", "phone call"),
                    ("visit", "visit in person"),
                    ("import", "automatically imported"),
                ],
                default="email",
                max_length=10,
            ),
        ),
    ]
