# Generated by Django 3.2.12 on 2022-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foirequestfollower", "0003_auto_20200319_1702"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="foirequestfollower",
            name="unique_user_follower",
        ),
        migrations.RemoveConstraint(
            model_name="foirequestfollower",
            name="unique_email_follower",
        ),
        migrations.RenameField(
            model_name="foirequestfollower",
            old_name="request",
            new_name="content_object",
        ),
        migrations.AddConstraint(
            model_name="foirequestfollower",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("content_object", "user"),
                name="unique_user_follower_foirequestfollower_foirequestfollower",
            ),
        ),
        migrations.AddConstraint(
            model_name="foirequestfollower",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("content_object", "email"),
                name="unique_email_follower_foirequestfollower_foirequestfollower",
            ),
        ),
    ]
