name: Froide CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - uses: j178/prek-action@v1

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fragdenstaat/fds-base
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: |
          uv sync
          playwright install --with-deps chromium
          pnpm install
      - name: Build frontend
        run: pnpm run build
      - name: Run tests
        run: |
          coverage run --branch -m pytest froide/
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
        env:
          DATABASE_URL: postgis://postgres:postgres@localhost/froide

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: froide
        ports:
          - 5432:5432
      elasticsearch:
        image: elasticsearch:8.14.3
        options: -e "discovery.type=single-node" -e "xpack.security.enabled=false" --expose 9200 --health-cmd "curl localhost:9200/_cluster/health" --health-interval 10s --health-timeout 5s --health-retries 10
        ports:
          - 9200:9200
