name: Update translations

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            setup.py
            requirements.txt
      - name: Install system-level dependencies
        run: sudo apt-get update && sudo apt-get install libxml2-dev libxslt1-dev python3-dev libgdal-dev gdal-bin libmagic-dev libmagickwand-dev gettext libpoppler-cpp-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt
          pip install -e .
      - name: Setup Git
        run: |
          git config user.name "fdsbot"
          git config user.email "119665132+fdsbot@users.noreply.github.com"
      - name: Compile translations
        run: make messagesde
      - name: Commit translations
        run: |
          git add **/django.po || true
          git commit -m "💬 update translation messages" || true
          git push -u origin main:weblate-source --force
