name: Open translation PR

on:
  push:
    branches:
      - weblate
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  translation-pr:
    name: "Create Translation PR"
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B main -H weblate --title 'Translations update from Weblate' --body '' --repo $GITHUB_REPOSITORY || true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
